apiVersion: batch/v1
kind: Job
metadata:
  name: timer
spec:
  template:
    spec:
      containers:
      - name: timer
        image: docker.io/tetchel/timer:latest
        command: [ "python", "/timer.py", "30" ]
        tty: true
        # env:
      restartPolicy: OnFailure
  backoffLimit: 4
